# Generated by Django 4.2.16 on 2024-11-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_color',
            field=models.CharField(default='#F6AA1C', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_icon',
            field=models.CharField(default='person', max_length=100),
        ),
    ]
