# Generated by Django 4.2.16 on 2024-11-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrecipe',
            unique_together=set(),
        ),
    ]
