# Generated by Django 4.2.16 on 2024-11-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_background',
            field=models.CharField(default='lightMode', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_primary',
            field=models.CharField(default='lightMode', max_length=100),
        ),
    ]
