# Generated by Django 4.2.16 on 2024-11-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_user_is_active'),
        ('backend', '0004_remove_friendrequest_status'),
    ]

    operations = [
    ]
